homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret hass_property_name
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 0
  unit_system: metric
  time_zone: !secret hass_timezone

  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   # base_url: hass.witkowski.ovh
#   use_x_forwarded_for: true
#   trusted_proxies: 10.0.0.1
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.10.10
    - 192.168.0.13

api:

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 4
  include:
    domains:
      - sensor
      - binary_sensor
      - light
      - timer
      - person
      - media_player
      - switch
#  exclude:
#    entities:
#      - binary_sensor.wiktor_motion_sensor
#   - sensor.aquaratemp01_temperature
#   - sensor.aquaratemp01_humidity
#   - sensor.aquaratemp01_pressure

camera:
  - platform: generic
    name: Living Room Camera
    stream_source: rtsp://192.168.30.52/ch0_1.h264
    still_image_url: http://192.168.30.52/image01.jpg

# google assistant
google_assistant:
  project_id: vibohass
  service_account: !include vibohass_service.json
  report_state: true

# Text to speech
tts:
  - platform: google_translate

telegram_bot:
  # - platform: broadcast
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids: !secret telegram_bot_main_chat_id

notify:
  - platform: telegram
    name: Nottifier
    chat_id: !secret telegram_bot_main_chat_id

spotify:
  client_id: !secret hass_spotify_client_id
  client_secret:
    !secret hass_spotify_client_secret

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

    #spotcast:
    #sp_dc: !secret sp_dc
    # sp_key: !secret sp_key

# to use with automations
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number:
  brightness_level:
    name: Brightness Level
    initial: 255
    min: 0
    max: 255
    step: 1

## SWITCH
switch: !include switch.yaml

### LIGHTS
light: !include light.yaml

## BINARY_SENSOR
binary_sensor: !include binary_sensor.yaml

## SENSOR
sensor: !include sensor.yaml

## GROUPS
group: !include groups.yaml

## AUTOMATIONS
automation: !include automations.yaml

## SCRIPTS
script: !include scripts.yaml

## SCENES
scene: !include scenes.yaml
