homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret hass_property_name
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 0
  unit_system: metric
  time_zone: !secret hass_timezone

  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: hass.witkowski.ovh
  use_x_forwarded_for: true
  trusted_proxies: 10.0.0.1

api:

mqtt:
  discovery: true
  broker: 192.168.0.5
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# google assistant
google_assistant:
  project_id: vibohass
  service_account: !include vibohass_service.json
  report_state: true
  exposed_domains:
    - switch
    - light
  entity_config:  
    switch.reboot_garage_sonoff:
      expose: false
    switch.kitchen_light_01:
      expose: false
    switch.audiolab_optical:
      expose: false
    switch.audiolab_video:
      expose: false
    switch.audiolab_coaxial:
      expose: false
    switch.mini01:
      expose: false
    switch.mini02:
      expose: false
    switch.mini03:
      expose: false
    switch.mini04:
      expose: false
    switch.mini05:
      expose: false
    switch.mini06:
      expose: false
    switch.mini07:
      expose: false
    switch.mini08:
      expose: false
    

# Text to speech
tts:
  - platform: google_translate

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_key
    allowed_chat_ids: !secret telegram_bot_main_chat_id

spotify:
  client_id: !secret hass_spotify_client_id
  client_secret: !secret hass_spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key


# climate:
#   - platform: climate_ip
#     config_file: 'samsung_2878.yaml'
#     cert: ''
#     #cert: 'ac14k_m.pem' 
#     # set as '' to skip certificate verification
#     ip_address: '192.168.0.87'
#     token: '988c5ad4-fc75-4d87-98aa-e4ce43ac9e02'
#     mac: 'BC:8C:CD:5E:5D:DD'
#     name: 'Zosia AC'
#     debug: false
#     poll: disable_ip

# to use with automations
input_boolean:
  moviemode:
    name: Movie Mode
    initial: off
  videoinput:
    name: Vide Input
    initial: off
  audioinput:
    name: Audio Input
    initial: off
  stairs_switch_auto_on:
    name: "Stairs Light Turned On Automatically"
    initial: off


# influxdb:
#   host: 192.168.0.5
#   include:
#     domains:
#       - sensor

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    consider_home: 1800
    exclude:
      - 192.168.0.99
      - 192.168.0.5
      - 192.168.0.10

switch:
  - platform: mqtt
    name: "Kitchen Light 01"
    state_topic: "stat/sw_kitchen_01/POWER"
    command_topic: "cmnd/sw_kitchen_01/POWER"
    availability_topic: "tele/sw_kitchen_01/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: Shelly Terrace Down
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/0"
    command_topic: "shellies/shellyswitch25-98F4ABF36920/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: Shelly Terrace Up
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/1"
    command_topic: "shellies/shellyswitch25-98F4ABF36920/relay/1/command"
    payload_on: "on"
    payload_off: "off"
    retain: false
    
  - platform: mqtt
    name: Shelly TV
    state_topic: "shellies/shellyswitch25-8CAAB5059118/relay/0"
    command_topic: "shellies/shellyswitch25-8CAAB5059118/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: Shelly TV Side
    state_topic: "shellies/shellyswitch25-8CAAB5059118/relay/1"
    command_topic: "shellies/shellyswitch25-8CAAB5059118/relay/1/command"
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: 'Screen'
    state_topic: 'rf_bridge/stat/RfCode'
    command_topic: 'rf_bridge/cmnd/Backlog'
    availability_topic: 'tele/rf_bridge/LWT'
    payload_available: 'Online'
    payload_not_available: 'Offline'
    payload_on: 'RfRaw AAB04D0508026C014A00C8008C10FEC081A081A0A0A08181A0A0A0A0A0A0A0A0A0A0A0A0A0A0A0A0A081A08181A0A0A0A081A08181A0A081A0A0A0A0A0A0A0A0A081A0A0A0A0818181818181A081B0A055;RfRaw 0'
    payload_off: 'RfRaw AAB04B04080276014000D210D6B081A081A0A0A08181A0A0A0A0A0A0A0A0A0A0A090A0A0A0A0A081908181A0A0A0A081A08181A0A081A0A0A0A0A0A0A0A0A0A0A0A081A0818181A081818181A0A055; RfRaw 0'
    optimistic: true

  - platform: mqtt
    name: 'Gate'
    # state_topic: 'rf_bridge2/stat/RfCode'
    command_topic: 'rf_bridge2/cmnd/Backlog'
    availability_topic: 'rf_bridge2/tele/LWT'
    payload_available: 'Online'
    payload_not_available: 'Offline'
    payload_on: 'RfRaw AAB0580404017C0EEC02E43CE63808080808080808080808081A0A08282A08282A082A0A0A0A082A082A0A0A0A0A082A0A082A0A0A082A0A0A082A082A0828282828282A082A0A0A08282A0A08282A0A0A0A0A0A0A0A082A0A0A0855'
    payload_off: 'RfRaw AAB0580404017C0EEC02E43CE63808080808080808080808081A0A08282A08282A082A0A0A0A082A082A0A0A0A0A082A0A082A0A0A082A0A0A082A082A0828282828282A082A0A0A08282A0A08282A0A0A0A0A0A0A0A082A0A0A0855'

  - platform: mqtt
    name: 'Garage Door'
    # state_topic: 'rf_bridge2/stat/RfCode'
    command_topic: 'rf_bridge2/cmnd/Backlog'
    availability_topic: 'rf_bridge2/tele/LWT'
    payload_available: 'Online'
    payload_not_available: 'Offline'
    payload_on: 'RfRaw AAB05A050401D601400F6E02EE4146481818180808080808080808283B083B083B08383B0B0B0B0B0B083B08383B0B0B083838383B0B08383B0B0B08383B0B08383B0B083B0B0B0B083B083B0B0B08383838383B083B0B0B0B083B0B0B55'
    payload_off: 'RfRaw AAB05A050401D601400F6E02EE4146481818180808080808080808283B083B083B08383B0B0B0B0B0B083B08383B0B0B083838383B0B08383B0B0B08383B0B08383B0B083B0B0B0B083B083B0B0B08383838383B083B0B0B0B083B0B0B55'

  - platform: template
    switches:
      movie_mode:
        friendly_name: "Movie Mode"
        value_template: >
          {{ is_state('input_boolean.moviemode', 'on') }}
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.moviemode
          - service: script.moviemode_on
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.moviemode
          - service: script.moviemode_off 
      video_input:
        friendly_name: "Video Input"
        value_template: >
          {{ is_state('input_boolean.videoinput', 'on') }}
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.videoinput
          - service: script.turn_on
            entity_id: script.audiolab_video
          - service: input_boolean.turn_off
            entity_id: input_boolean.audioinput
        turn_off:
          - service: input_boolean.turn_on
            entity_id: input_boolean.audioinput
          - service: script.turn_on
            entity_id: script.audiolab_audio
          - service: input_boolean.turn_off
            entity_id: input_boolean.videoinput
      audio_input:
        friendly_name: "Audio Input"
        value_template: >
          {{ is_state('input_boolean.audioinput', 'on') }}
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.audioinput
          - service: script.turn_on
            entity_id: script.audiolab_audio
          - service: input_boolean.turn_off
            entity_id: input_boolean.videoinput
        turn_off:
          - service: input_boolean.turn_on
            entity_id: input_boolean.videoinput
          - service: script.turn_on
            entity_id: script.audiolab_video
          - service: input_boolean.turn_off
            entity_id: input_boolean.audioinput


### LIGHTS
light:
  - platform: group
    name: Inside Lights
    entities:
      - light.downstairs_lights
      - light.upstairs_lights

  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_upper
      - light.kitchen_table
      - light.kitchen_cabinet

  - platform: group
    name: Living Room Lights
    entities:
      - light.tv
      - light.tv_side
      - light.zosia_wall

  - platform: group
    name: Downstairs Lights
    entities:
      - light.living_room_lights
      - light.kitchen_lights
      - light.stairs
      - light.stairs_christmas
      - light.hall
      - light.garage_sonoff_light

  - platform: group
    name: Upstairs Lights
    entities:
      - light.zosia
      - light.wiktor
      - light.upper_hall

  - platform: switch
    name: "Kitchen Upper"
    entity_id: switch.kitchen_Light_01

  - platform: switch
    name: "Zosia"
    entity_id: switch.mini01

  - platform: switch
    name: "Zosia Wall"
    entity_id: switch.ikeaplug01_switch

  - platform: switch
    name: "Kitchen Cabinet"
    entity_id: switch.mini04

  - platform: switch
    name: "Kitchen Table"
    entity_id: switch.mini03

  - platform: switch
    name: "Hall"
    entity_id: switch.mini06
  
  - platform: switch
    name: "Wiktor"
    entity_id: switch.mini02

  - platform: switch
    name: "Porch"
    entity_id: switch.mini05

  - platform: switch
    name: "Terrace 1"
    entity_id: switch.terrace1

  - platform: switch
    name: "Terrace 2"
    entity_id: switch.terrace2

  - platform: switch
    name: "Terrace 3"
    entity_id: switch.terrace3

  - platform: switch
    name: "Terrace Down"
    entity_id: switch.shelly_terrace_down

  - platform: switch
    name: "Upper Hall"
    entity_id: switch.mini08

  - platform: switch
    name: "Stairs"
    entity_id: switch.mini07

  - platform: switch
    name: "TV"
    entity_id: switch.shelly_tv

  - platform: switch
    name: "TV Side"
    entity_id: switch.shelly_tv_side

  - platform: switch
    name: "Stairs Christmas"
    entity_id: switch.ikeaplug03

ecovacs:
  username: vibowit@gmail.com
  password: !secret deebot_pass
  country: pl
  continent: eu

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature
      - humidity
      - pressure
      - wind_speed
      - moon_phase
      - sunrise_time
      - sunset_time

  - platform: mqtt
    name: 'Shelly Terrace Down Power'
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/0/power"
    unit_of_measurement: "Watts"

  - platform: mqtt
    name: 'Shelly Terrace Down Energy'
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/0/energy"
    unit_of_measurement: "kWh"

  - platform: mqtt
    name: 'Shelly Terrace Up Power'
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/1/power"
    unit_of_measurement: "Watts"

  - platform: mqtt
    name: 'Shelly Terrace Up Energy'
    state_topic: "shellies/shellyswitch25-98F4ABF36920/relay/1/energy"
    unit_of_measurement: "kWh"


binary_sensor:
  - platform: mqtt
    name: 'Blue Button'
    state_topic: 'rf_bridge/tele/RESULT'
    value_template: >-
      {% if value_json.RfReceived.Data == 'F92001' %}
        {{'ON'}}
      {% else %}
        {{states('binary_sensor.blue_button') | upper}}
      {% endif %}
    off_delay: 15

  - platform: mqtt
    name: Shelly Terrace Down
    state_topic: "shellies/shellyswitch25-98F4ABF36920/input/0"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: Shelly Terrace Up
    state_topic: "shellies/shellyswitch25-98F4ABF36920/input/1"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: Shelly TV
    state_topic: "shellies/shellyswitch25-8CAAB5059118/input/0"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: Shelly TV Side
    state_topic: "shellies/shellyswitch25-8CAAB5059118/input/1"
    payload_on: "1"
    payload_off: "0"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
