---
substitutions:
  device: garage_door
  name: "Garage Door"
  # Name for the relays
  reboot_timeout: 2d
  update_interval: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini

<<: !include common/common.yaml
# Enable logging
logger:
  level: INFO

web_server:
  port: 80

switch:
  - platform: gpio
    name: "${name} Switch"
    pin: D2
    id: garage_relay
    #inverted: yes
    internal: true
    
  - platform: template
    name: "Garage Remote"
    icon: "mdi:garage"
    turn_on_action:
    - switch.turn_on: garage_relay
    - delay: 500ms
    - switch.turn_off: garage_relay

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
    name: "${name}"
    device_class: door

#sensor:
#  - platform: ultrasonic
#    trigger_pin: D7
#    echo_pin: D8
#    name: "Ultrasonic Sensor"
#    update_interval: 20s
#    timeout: 2.0m
