---
substitutions:
  device: livingroom_audio_switches
  name: "Living Room Audio Switches"
  # Name for the relays
  channel_1: "Audiolab Switch"
  reboot_timeout: 2d
  update_interval: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
# Enable logging
logger:
  level: INFO

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${channel_1} Button"
  - platform: status
    name: "${name} Status"

switch:
  - platform: gpio
    name: "${channel_1}"
    pin: GPIO12

