---
substitutions:
  device: wiktor_temp
  name: Wiktor Temperature
  location: ${name}
  reboot_timeout: 2d
  update_interval: 5min

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcu

<<: !include common/common.yaml
# <<: !include common/sensors.yaml

# Enable logging
logger:
  level: INFO

# Temp and Humidity sensor setup
sensor:
  - platform: dht
    model: DHT11
    pin: D7
    temperature:
      name: "Wiktor Room Temperature"
      filters:
        offset: -1.0  
      
    humidity:
      name: "Wiktor Room Humidity"
    update_interval: 120s
    
binary_sensor:
  - platform: gpio
    pin: D5
    name: "Wiktor Motion Sensor"
    device_class: motion
    